### ISSUE TITLE
Create a "list" in HubSpot for folks in Alpha/Beta and eventually "Customers"

### ISSUE THREAD

**Issue by afolson** [meltano/support#2]
The support portal can be accessed by a HubSpot list of specific users and companies. They'll automatically be sent an email to register which will grant them access to see a list of open/closed tickets.

**Comment by afolson** [comment]
See #1 for info on how to play around with the portal and lists

**Comment by DouweM** [comment]
Right now we have this list: https://app.hubspot.com/contacts/20712484/objects/0-2/views/10066274/list?redirectFrom=crm-records-ui for anyone who's signed up for the waitlist, we can likely filter that down to "Alpha - Onboarding" to give those access to the support portal.

**Comment by afolson** [comment]
@DouweM I think that will work for now. If we end up needing a static list of people I can open another issue. Thanks!
